spring:
  application:
    name: car
  datasource:
     url: 'jdbc:mysql://47.104.7.73:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false'
     username: root
     password: 123456
     driver-class: 'com.mysql.jdbc.Driver'
     database-name: car
     init-sql: mysql/init.sql

server:
  port: 80
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true