
CREATE TABLE IF NOT EXISTS rds_db_instance(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  db_instance_status_desc VARCHAR(255) DEFAULT NULL,
  db_instance_id VARCHAR(255) DEFAULT NULL,
  db_instance_used_type VARCHAR(255) DEFAULT NULL,
  engine VARCHAR(255) DEFAULT NULL,
  db_instance_name VARCHAR(255) DEFAULT NULL,
  uid VARCHAR(255) DEFAULT NULL,
  user_id VARCHAR(255) DEFAULT NULL,
  session_usage VARCHAR(255) DEFAULT NULL,
  disk_usage VARCHAR(255) DEFAULT NULL,
  iops_usage VARCHAR(255) DEFAULT NULL,
  cpu_usage VARCHAR(255) DEFAULT NULL,
  db_instance_type VARCHAR(255) DEFAULT NULL,
  db_instance_conn_type VARCHAR(255) DEFAULT NULL,
  engine_version VARCHAR(255) DEFAULT NULL,
  db_instance_cpu_cores VARCHAR(255) DEFAULT NULL,
  db_instance_create_time VARCHAR(255) DEFAULT NULL,
  max_connections VARCHAR(255) DEFAULT NULL,
  db_instance_storage VARCHAR(255) DEFAULT NULL,
  db_instance_memory VARCHAR(255) DEFAULT NULL,
  max_qps VARCHAR(255) DEFAULT NULL,
  max_iops VARCHAR(255) DEFAULT NULL,
  lock_mode VARCHAR(255) DEFAULT NULL,
  cluster_name VARCHAR(255) DEFAULT NULL,
  region VARCHAR(255) DEFAULT NULL,
  annual_usage VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS rds_db_instance_host_info(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  db_instance_id VARCHAR(255) DEFAULT NULL,
  site_name VARCHAR(50) DEFAULT NULL,
  host_ip VARCHAR(50) DEFAULT NULL,
  host_port VARCHAR(50) DEFAULT NULL,
  instance_id VARCHAR(50) DEFAULT NULL
) DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS rds_user(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  uid VARCHAR(50) NOT NULL,
  user_id VARCHAR(50) NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS rds_error_log(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  error_info VARCHAR(255) DEFAULT NULL,
  error_id VARCHAR(255) DEFAULT NULL,
  create_time VARCHAR(255) DEFAULT NULL,
  create_time_stamp BIGINT DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS rds_db_instance_unavailable_record(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  recover_time VARCHAR(255) DEFAULT NULL,
  recover_time_stamp BIGINT DEFAULT NULL,
  error_time VARCHAR(255) DEFAULT NULL,
  error_time_stamp BIGINT DEFAULT NULL,
  failure_id VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS rds_slow_log_record(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  slow_log_id VARCHAR(255) DEFAULT NULL,
  host_address VARCHAR(255) DEFAULT NULL,
  db_name VARCHAR(255) DEFAULT NULL,
  sql_id VARCHAR(255) DEFAULT NULL,
  sql_text VARCHAR(255) DEFAULT NULL,
  query_time VARCHAR(255) DEFAULT NULL,
  lock_time VARCHAR(255) DEFAULT NULL,
  parse_row_numbers VARCHAR(255) DEFAULT NULL,
  return_item_numbers VARCHAR(255) DEFAULT NULL,
  query_start_time VARCHAR(255) DEFAULT NULL,
  query_start_time_stamp BIGINT DEFAULT NULL,
  account_name VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS rds_host_instance(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  db_instance_host_info_id INT UNSIGNED NOT NULL,
  instance_id VARCHAR(255) DEFAULT NULL,
  site_name VARCHAR(255) DEFAULT NULL,
  role VARCHAR(255) DEFAULT NULL,
  host_ip VARCHAR(255) DEFAULT NULL,
  host_port VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;


